#include<iostream>
#include<vector>

using namespace std;

/** this program helps with the details of each data file name which 
    was generated by the AluSimulator. It gives an detailed 
    description such as what was the input genome, how many ALUs 
    inserted,how many + and - ALUs, and the referece file. 
**/

int main(){
   cout<< "file name is:" << inputFile <<endl;
   cout<< "ALUs inserted:" << aluNum << endl;
   cout<< "positions of ALUs:" << position <<endl;
   cout<< "+ or -:" << property << endl; 
}
